### ISSUE TITLE
Unknown function 'set'

### ISSUE THREAD

**Issue by stony245** [jonglissimo/Light-Control-Chataigne-Module#1]
Hello,

I have setup a State in Chataigne 1.7.3 to trigger Lights when a Midi note comes in. However I receive the following message, when  the state is triggered:
`Line 209, column 16 : Unknown function 'set'`
and nothing happens on the Artnet side.

**Comment by manuelmitasch** [comment]
This looks like it can't find your fixture container when trying to set the color. Most likely there is something wrong with your fixture-defintion.json and fixtures.json files. Can you please provides the two json config files and an example Chataigne file, so I can try to repoduce this.

I will for sure add a better debug message for this case.

**Comment by manuelmitasch** [comment]
@stony245 It could also be an issue with names for lights containing capital letters or symbols. This is currently limited to lower case letters and numbers. It has todo with how Chataigne creates internal scripting addresses. I need to find a better way to circumvent this.

**Comment by manuelmitasch** [comment]
@stony245  I have just pushed a new version with better error messages and the naming convention/limitation mentioned in the readme.

**Comment by stony245** [comment]
Thank you. It turned out that I named the fixture wrongly in Chataigne. Sorry about the circumstances.

**Comment by stony245** [comment]
By the way: I love this module. Makes light control in Chatiagne much easier. Thank you for your good work!
